# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f241fcd754e889fbd220d227cb6a325378bb5cd160a69b7707680bb3722b01e8c0ad8c105d8f099433fcbc40f52f8600b3569be1aef5ef20c51ddbd1d144cf10

test:
  secret_key_base: e30972a4668ec2ac7357f6e012d2cdfc26c291f973ee69d8737e3d68479160f7e7e09b83088523d0e5bd3b9bb9a16e8ac9ed0bae50adb1b0d24a4f706f0d274a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
